apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: atlas
  labels:
    name: atlas
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: atlas
    spec:
      containers:
      - name: atlas
        image: daocloud.io/troyying/atlas:master-949e741
        imagePullPolicy: IfNotPresent
        env:
          - name: MYSQL_MASTER_HOST
            value: 'mysql-master'
          - name: MYSQL_SLAVE_HOST
            value: 'mysql-slave'
          - name: MYSQL_USERNAME
            value: 'root'
          - name: MYSQL_PASSWORD
            value: 'demo'
        ports:
        - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: atlas
spec:
  ports:
  - name: client
    port: 3306
    protocol: TCP
  selector:
    name: atlas
