apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: wordpress
  labels:
    name: wordpress
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:php7.0
        imagePullPolicy: IfNotPresent
        env:
          - name: WORDPRESS_DB_HOST
            value: 'atlas'
          - name: WORDPRESS_DB_USER
            value: 'root'
          - name: WORDPRESS_DB_PASSWORD
            value: 'demo'
          - name: WORDPRESS_DB_NAME
            value: 'demo'
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    name: wordpress
  type:
     NodePort
