apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql-slave
  labels:
    name: mysql-slave
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql-slave
    spec:
      containers:
      - name: mysql-slave
        image: caesaryty/mysql-slave:5.7
        imagePullPolicy: IfNotPresent
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: 'demo'
          - name: MYSQL_DATABASE
            value: 'demo'
          - name: MYSQL_REPLICATION_USER
            value: 'repl'
          - name: MYSQL_REPLICATION_PASSWORD
            value: 'slave'
          - name: MYSQL_MASTER_SERVICE_HOST
            value: 'mysql-master'
        ports:
        - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
spec:
  ports:
  - port: 3306 # the port that this service should serve on
    # the container on each pod to connect to, can be a name
    # (e.g. 'www') or a number (e.g. 80)
    targetPort: 3306
    protocol: TCP
  # just like the selector in the replication controller,
  # but this time it identifies the set of pods to load balance
  # traffic to.
  selector:
    name: mysql-slave
